name: 'FIXME alert'
description: 'Check code for specific terms (FIXME, WIP, etc.) and fail (with code annotations) if any are found.'
author: '@bbugh'
branding:
  icon: 'list'  
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  terms:
    description: 'The pipe-delimited searchable terms to pass as a regex group to `git grep`.'
    required: false
    default: "FIXME"
