name: "Self-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        terms: "wip|fix|fixme"
      env:
        ENVIRONMENT: test
